import React, { useMemo, useState } from 'react';
import { BarChart3, Bot, CalendarDays, Check, ChevronDown, ChevronRight, Clock3, Download, MessageCircle, RefreshCw, Search, ShieldCheck, Smile, Target, TrendingUp, Users } from 'lucide-react';

function PageHeader({ eyebrow, title, description, action }) {
  return <div className="flex flex-wrap items-end justify-between gap-4 border-b border-slate-200 bg-white px-8 py-6">
    <div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-600">{eyebrow}</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action}
  </div>;
}

function AgentsPage({ agents = [], onAction }) {
  return <><PageHeader eyebrow="Workspace" title="AI agents" description="Choose and manage assistants available to your organization." action={<button onClick={() => onAction('Agent builder opened')} className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white hover:bg-violet-700">+ Create agent</button>} />
    <div className="grid gap-4 p-8 sm:grid-cols-2 xl:grid-cols-3">{agents.map((agent) => <button key={agent.name} onClick={() => onAction(`${agent.name} opened`)} className="group rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md">
      <div className="flex items-start justify-between"><div className={`relative flex h-11 w-11 items-center justify-center overflow-hidden rounded-xl ${agent.color}`}><Bot size={21}/><img src={agent.image} onError={(event) => { event.currentTarget.style.display = 'none'; }} alt="" className="absolute inset-0 h-full w-full object-cover"/></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${agent.status === 'Active' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{agent.status}</span></div>
      <h2 className="mt-4 font-bold text-slate-900">{agent.name}</h2><p className="mt-1 text-sm leading-5 text-slate-500">{agent.description}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-xs text-slate-500"><span>{agent.category}</span><span className="flex items-center gap-1 font-semibold text-violet-600">{agent.conversations} chats <ChevronRight size={14}/></span></div>
    </button>)}</div></>;
}

function UsersPage({ users = [], onAction }) {
  const [category, setCategory] = useState('All'); const [query, setQuery] = useState('');
  const categories = ['All', 'Engineering', 'People', 'Sales', 'Finance'];
  const filtered = useMemo(() => users.filter((u) => (category === 'All' || u.department === category) && `${u.name} ${u.email}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  return <><PageHeader eyebrow="Directory" title="Users" description="Browse people by team, role and account status." action={<button onClick={() => onAction('Invite form opened')} className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white">Invite user</button>} />
    <div className="p-8"><div className="mb-4 flex flex-wrap gap-3"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search users..." className="w-full rounded-xl border border-slate-200 bg-white py-2 pl-10 pr-3 text-sm"/></div>{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-xl px-3 py-2 text-sm font-medium ${category === item ? 'bg-violet-600 text-white' : 'border border-slate-200 bg-white text-slate-600'}`}>{item}</button>)}</div>
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="grid grid-cols-[2fr_1fr_1fr_100px] gap-3 bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wide text-slate-400"><span>User</span><span>Department</span><span>Role</span><span>Status</span></div>{filtered.map((user) => <button key={user.email} onClick={() => onAction(`${user.name}'s profile opened`)} className="grid w-full grid-cols-[2fr_1fr_1fr_100px] items-center gap-3 border-t border-slate-100 px-5 py-4 text-left hover:bg-violet-50/40"><span className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-900 text-xs font-bold text-white">{user.name.split(' ').map(n => n[0]).join('')}</span><span><strong className="block text-sm text-slate-800">{user.name}</strong><small className="text-slate-400">{user.email}</small></span></span><span className="text-sm text-slate-600">{user.department}</span><span className="text-sm text-slate-600">{user.role}</span><span className="text-xs font-semibold text-emerald-600">● {user.status}</span></button>)}</div>
    </div></>;
}

function SettingsPage({ onAction }) {
  const [settings, setSettings] = useState({ history: true, citations: true, suggestions: true, sound: false });
  const toggle = (key) => setSettings((s) => ({ ...s, [key]: !s[key] }));
  const rows = [['history', 'Save conversation history', 'Keep chats available in the conversation list.'], ['citations', 'Show source citations', 'Include references with grounded answers.'], ['suggestions', 'Suggested prompts', 'Show helpful prompts above the message field.'], ['sound', 'Response sounds', 'Play a subtle sound when an answer is ready.']];
  return <><PageHeader eyebrow="Preferences" title="Settings" description="Manage general workspace and conversation behaviour." />
    <div className="mx-auto w-full max-w-4xl space-y-5 p-8"><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-bold text-slate-900">General</h2><label className="mt-5 block text-sm font-semibold text-slate-700">Display name<input defaultValue="Sriram" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label><label className="mt-4 block text-sm font-semibold text-slate-700">Language<select className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 font-normal"><option>English</option><option>Hindi</option><option>Tamil</option></select></label></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-bold text-slate-900">Conversation settings</h2><div className="mt-3 divide-y divide-slate-100">{rows.map(([key, title, description]) => <div key={key} className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-semibold text-slate-800">{title}</p><p className="text-xs text-slate-500">{description}</p></div><button role="switch" aria-checked={settings[key]} onClick={() => toggle(key)} className={`relative h-6 w-11 rounded-full transition ${settings[key] ? 'bg-violet-600' : 'bg-slate-300'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${settings[key] ? 'left-6' : 'left-1'}`}/></button></div>)}</div></section>
      <button onClick={() => onAction('Settings saved')} className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white"><Check className="mr-2 inline" size={16}/>Save changes</button></div></>;
}

function AnalyticsPage({ onAction }) {
  const [tab, setTab] = useState('Overview');
  const [compare, setCompare] = useState(true);
  const stats = [
    ['Total Sessions', '18,742', '+12.7%', TrendingUp, '#4f46e5'], ['Active Users', '6,231', '+16.3%', Users, '#6366f1'],
    ['Messages Handled', '95,816', '+18.8%', MessageCircle, '#0891b2'], ['Resolution Rate', '87.3%', '+8.2%', Target, '#7c3aed'],
    ['Avg. Response Time', '3.24 sec', '-3.4%', Clock3, '#2563eb'], ['User Satisfaction', '4.6 / 5', '+4.6%', Smile, '#059669'],
  ];
  const tabs = ['Overview', 'Usage', 'Adoption', 'Agents', 'Knowledge', 'Quality', 'Cost'];
  const points = '0,72 28,59 56,63 84,45 112,54 140,31 168,38 196,19 224,30 252,27 280,12 308,25 336,18 364,37 392,28 420,9 448,20 476,15';
  const Card = ({ title, children, className = '' }) => <section className={`rounded-xl border border-slate-200 bg-white p-4 shadow-sm ${className}`}><h2 className="mb-3 text-sm font-bold text-slate-800">{title}</h2>{children}</section>;
  return <div className="min-w-[900px] p-6 text-slate-800">
    <div className="flex items-start justify-between gap-6"><div><h1 className="text-2xl font-bold tracking-tight">Agent Analytics</h1><p className="mt-1 text-sm text-slate-500">Monitor adoption, usage and performance across all MyLiva agents.</p></div><div className="flex gap-2"><button onClick={() => onAction('Analytics shared')} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold">Share</button><button onClick={() => onAction('Analytics report downloaded')} className="flex items-center gap-2 rounded-lg bg-violet-600 px-3 py-2 text-xs font-semibold text-white"><Download size={14}/> Export report</button></div></div>
    <div className="mt-5 flex flex-wrap items-center gap-2">{[['Last 90 days', CalendarDays], ['All channels', BarChart3], ['All departments', Users], ['All locations', Target]].map(([label, Icon]) => <button key={label} onClick={() => onAction(`${label} filter opened`)} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-medium"><Icon size={14}/>{label}<ChevronDown size={13}/></button>)}<button onClick={() => setCompare(!compare)} className="ml-2 flex items-center gap-2 text-xs"><span className={`relative h-5 w-9 rounded-full ${compare ? 'bg-violet-600' : 'bg-slate-300'}`}><span className={`absolute top-1 h-3 w-3 rounded-full bg-white transition-all ${compare ? 'left-5' : 'left-1'}`}/></span>Compare with previous period</button><button onClick={() => onAction('Analytics refreshed')} className="ml-auto flex items-center gap-1 text-xs font-semibold text-violet-700"><RefreshCw size={14}/> Refresh</button></div>
    <div className="mt-4 flex gap-7 border-b border-slate-200">{tabs.map((item) => <button key={item} onClick={() => { setTab(item); onAction(`${item} analytics selected`); }} className={`border-b-2 px-1 pb-3 text-xs font-semibold ${tab === item ? 'border-violet-600 text-violet-700' : 'border-transparent text-slate-500'}`}>{item}</button>)}</div>

    <div className="mt-4 grid grid-cols-6 gap-3">{stats.map(([label,value,change,Icon,color], index) => <button key={label} onClick={() => onAction(`${label} details opened`)} className="rounded-xl border border-slate-200 bg-white p-3 text-left shadow-sm"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-50" style={{color}}><Icon size={17}/></span><span className="text-[11px] font-medium text-slate-600">{label}</span></div><p className="mt-2 text-xl font-bold">{value}</p><p className={`mt-1 text-[10px] font-semibold ${change.startsWith('-') ? 'text-rose-600' : 'text-emerald-600'}`}>{change} <span className="font-normal text-slate-400">vs previous</span></p><svg viewBox="0 0 120 24" className="mt-2 h-6 w-full" preserveAspectRatio="none"><polyline points={index % 2 ? '0,19 15,14 30,17 45,9 60,15 75,7 90,12 105,4 120,8' : '0,20 15,16 30,18 45,11 60,14 75,7 90,10 105,3 120,6'} fill="none" stroke={color} strokeWidth="2"/></svg></button>)}</div>

    <div className="mt-3 grid grid-cols-12 gap-3"><Card title="Agent Usage Trend" className="col-span-5"><div className="mb-2 flex gap-4 text-[10px] text-slate-500"><span className="text-blue-600">● Sessions</span><span className="text-cyan-600">● Messages</span><span className="text-violet-600">● Unique users</span></div><svg viewBox="0 0 480 130" className="h-36 w-full" preserveAspectRatio="none"><g stroke="#e2e8f0" strokeWidth="1">{[20,50,80,110].map(y => <line key={y} x1="0" y1={y} x2="480" y2={y}/>)}</g><polyline points={points} fill="none" stroke="#2563eb" strokeWidth="2.5"/><polyline points="0,105 28,95 56,98 84,82 112,88 140,70 168,78 196,59 224,66 252,61 280,48 308,57 336,50 364,65 392,55 420,39 448,46 476,41" fill="none" stroke="#06b6d4" strokeWidth="2"/></svg></Card>
      <Card title="Usage by Channel" className="col-span-3"><div className="flex items-center gap-5"><div className="flex h-28 w-28 items-center justify-center rounded-full" style={{background:'conic-gradient(#2563eb 0 56%, #6366f1 56% 72%, #06b6d4 72% 87%, #8b5cf6 87% 96%, #f59e0b 96%)'}}><div className="flex h-16 w-16 flex-col items-center justify-center rounded-full bg-white"><b>18,742</b><span className="text-[9px] text-slate-400">Sessions</span></div></div><div className="space-y-2 text-[10px]">{[['Web application','56.1%'],['Microsoft Teams','16.0%'],['Mobile app','14.6%'],['SharePoint','9.4%']].map(x => <p key={x[0]} className="flex justify-between gap-4"><span>{x[0]}</span><b>{x[1]}</b></p>)}</div></div></Card>
      <Card title="Peak Usage Heatmap" className="col-span-4"><div className="grid grid-cols-12 gap-1">{Array.from({length:84}, (_,i) => <span key={i} className="h-3 rounded-[2px] bg-violet-600" style={{opacity: .08 + (((i * 7 + Math.floor(i/12)*3) % 10) / 12)}}/> )}</div><div className="mt-3 flex justify-between text-[9px] text-slate-400"><span>12 AM</span><span>8 AM</span><span>12 PM</span><span>8 PM</span></div><div className="mt-4 h-1.5 rounded bg-gradient-to-r from-violet-50 to-violet-700"/></Card>
    </div>

    <div className="mt-3 grid grid-cols-12 gap-3"><Card title="Answer Quality & Reliability" className="col-span-4"><div className="flex items-center gap-6"><div className="flex h-24 w-24 items-center justify-center rounded-full border-[10px] border-violet-600"><div className="text-center"><b>85 / 100</b><p className="text-[9px] text-emerald-600">Excellent</p></div></div><div className="space-y-2 text-[10px]"><p>● Complete & relevant <b className="float-right ml-5">60%</b></p><p>● Partially relevant <b className="float-right">25%</b></p><p>● Irrelevant <b className="float-right">10%</b></p><p>● Not fully grounded <b className="float-right">5%</b></p></div></div></Card>
      <Card title="Knowledge Source Performance" className="col-span-5"><div className="grid grid-cols-[1.5fr_repeat(3,1fr)] gap-2 border-b pb-2 text-[9px] font-bold text-slate-400"><span>Source</span><span>Positive</span><span>Neutral</span><span>Score</span></div>{[['DWS GenAI Engineering','62.1%','22.1%','91.5%'],['Technical Docs','57.8%','24.4%','90.5%'],['SharePoint','55.4%','26.0%','89.1%'],['HR Policies','54.6%','24.5%','88.3%']].map(r => <div key={r[0]} className="grid grid-cols-[1.5fr_repeat(3,1fr)] gap-2 py-2 text-[10px]"><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]}</span><span className="font-bold text-emerald-600">{r[3]}</span></div>)}</Card>
      <Card title="User Feedback & Sentiment" className="col-span-3"><div className="flex items-center gap-5"><div className="flex h-24 w-24 items-center justify-center rounded-full" style={{background:'conic-gradient(#10b981 0 62%, #3b82f6 62% 85%, #fb7185 85%)'}}><div className="flex h-14 w-14 items-center justify-center rounded-full bg-white font-bold">62%</div></div><div className="space-y-3 text-[10px]"><p className="text-emerald-600">● Positive 62.1%</p><p className="text-blue-600">● Neutral 22.7%</p><p className="text-rose-500">● Negative 15.2%</p></div></div></Card></div>

    <div className="mt-3 grid grid-cols-3 gap-3"><Card title="Cost & Performance Analytics"><div className="grid grid-cols-3 gap-3 text-xs"><div><p className="text-slate-400">Token use</p><b className="text-lg">52.0B</b></div><div><p className="text-slate-400">Cost / chat</p><b className="text-lg">$13.30</b></div><div><p className="text-slate-400">P95 response</p><b className="text-lg">2.45 sec</b></div></div><div className="mt-4 h-2 rounded bg-gradient-to-r from-blue-600 via-violet-500 to-slate-200"/></Card><Card title="Recent Alerts"><div className="space-y-2 text-[10px]"><p className="flex justify-between"><span className="text-rose-600">● Unanswered questions increased</span><b>High</b></p><p className="flex justify-between"><span className="text-amber-600">● Web search error rate spike</span><b>Medium</b></p><p className="flex justify-between"><span className="text-blue-600">● IT support latency threshold</span><b>Low</b></p></div></Card><Card title="AI-Generated Key Insight"><p className="text-sm font-semibold">Peak usage occurs between 10 AM – 2 PM on weekdays.</p><span className="mt-3 inline-block rounded-full bg-violet-50 px-2 py-1 text-[10px] font-semibold text-violet-700">High impact</span></Card></div>
  </div>;
}

export default function WorkspacePage({ page, data = {}, onAction }) {
  if (page === 'agents') return <AgentsPage agents={data.agents} onAction={onAction}/>;
  if (page === 'users') return <UsersPage users={data.users} onAction={onAction}/>;
  if (page === 'settings') return <SettingsPage onAction={onAction}/>;
  return <AnalyticsPage onAction={onAction}/>;
}
